# render.yaml
services:
  - type: web
    name: solo-leveling-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_PATH
        value: "/data/users.json"
    disk:
      name: bot-data
      mountPath: /data
